name: Testing
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    name: Testing iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable     
      - name: Testing iOS app
        run: xcodebuild -project WikiLocation.xcodeproj -scheme WikiLocation -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1' clean test | xcpretty
